apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: "drupal"
  name: drupal-0
  namespace: gui865
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: "drupal"
  type: LoadBalancer
status:
  loadBalancer: {}
